#%RAML 0.8
title: food-crave
version: v1
baseUri: http://ritwik-dell-test.apigee.net/food-crave/{version}

schemas:
  - fbuser: |
      {
        "type" : "object",
        "required": [
            "response-status"
        ],
        "properties": {
            "userDetails": {
                "type": "object",
                "required": [
                    "name",
                    "email"
                ],
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "user name"
                    },
                    "first_name": {
                        "type": "string",
                        "description": "user first name"
                    },
                    "location": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "description": "location (if present) name as returned from Facebook"
                            }
                        }
                    },
                    "email": {
                        "type": "string",
                        "description": "user email id"
                    }
                }
            },
            "response-status": {
                "$ref": "#/definitions/Response-status"
            }
        }
      }
  - restaurant-response: |
      type: "object"
      required:
        - "response-status"
      properties:
        page-size:
          type: "number"
        offset:
          type: "number"
        total-records:
          type: "number"
        data:
          type: "array"
          items:
            $ref: "Restaurant"
        response-status:
          $ref: "Response-status"

  - restaurant: |
      type: object
      properties:
        name:
          type: string
          description: Restaurant name
        id:
          type: string
          description: Restaurant id
        url:
          type: string
          description: restaurant  url
        mobile_url:
          type: string
          description: restaurant mobile url
        location:
          description: Location of the restaurant
          $ref: 'Location'
        is_closed:
          type: boolean
          description: Whether the business has been permanently closed
        display_phone:
          type: string
          description: restaurant phone number formatted for display
        rating:
          type: number
          description: restaurant review ratings on Yelp
        review_count:
          type: number
          description: number of reviews on Yelp
        rating_img_url:
          type: string
          description: URL to star rating image for this restaurant
        categories:
          type: array
          items:
            $ref: 'Category'

  - category: |
      type: array
      items:
        type: string

  - location: |
      type: object
      properties:
        display_address:
          type: array
          description: Address of the restaurant
          items:
            type: string
        geo-accuracy:
          type: string
          description: accuracy of the coordinates provided
        coordinate:
          type: object
          properties:
            latitude:
              type: string
              description: latitude coordinates for the restaurant
            longitude:
              type: string
              description: longitude coordinates for the restaurant

  - response-status: |
      type: object
      required:
        - status
        - http-code
      properties:
        status:
          type: string
          description: Status of the request.
          enum:
            - success
            - success with warnings
            - failure
        http-code:
          type: integer
          description: HTTP-Code being returned
          enum:
            - 200
            - 400
            - 401
            - 404
            - 500
        error-block:
          $ref: 'error-block'

  - error-block: |
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: 'error'
  - error: |
      type: object
      required:
        - error-code
        - error-message
        - error-details
      properties:
        error-code:
          type: string
          description: The particular error-code being returned
        error-message:
          type: string
          description: Short error-message
        error-details:
          type: string
          description: Detailed error-message
        help-url:
          type: string
          description: URL for additional resources



/fbusers/{uid}:
  displayName: Facebook Users
  description: Specific user details

  get:
    description: Get a specific fbuser by Id
    queryParameters:
      accesstoken:
        description: User access token to access user details
        type: string
        required: true

    responses:
      200:
        description: Facebook user profile information for the given user fetched from Facebook
        body:
          application/json:
            schema: fbuser

/restaurants:
  description: Collection of restaurants

  get:
    description: Collection of restaurants with the given search criteria
    queryParameters:
      address:
        displayName: address
        description: Address near which restaurant needs to be fetched
        required: true
        type: string
      food-pref:
        description: The food/cuisine preference of the user
        required: false
        type: string
      page-size:
        description: Number of restaurant details (or size of resultset) desired
        required: false
        type: integer
        minimum: 1
        maximum: 15
        default: 10
      offset:
        description: 'To fetch the next set of results, offset the result-set by this amount'
        required: false
        type: integer
        minimum: 0
        default: 0
      distance:
        description: The radial distance in kilometers (KMs) from the location from where to fetch the restaurants for
        required: false
        type: integer
        minimum: 1
        maximum: 40
        default: 40
    headers:
      content-type:
        description: Content-type in which communication needs to happen
        required: true
        type: string
        enum: [application/json, application/xml]
    responses:
      200:
        description: Response for successful request
        body:
          application/json:
            schema: restaurant-response
      400:
        description: Response for bad request
        body:
          application/json:
            schema: restaurant-response
      401:
        description: Response for unauthorized request
        body:
          application/json:
            schema: restaurant-response
      404:
        description: Response for resource not found
        body:
          application/json:
            schema: restaurant-response
      500:
        description: Response for internal error
        body:
          application/json:
            schema: restaurant-response


/restaurants/{id}:
  description: Specific restaurant details

  get:
    description: Get a specific restaurant by Id
    headers:
      content-type:
        description: Content-type in which communication needs to happen
        required: true
        type: string
        enum: [application/json, application/xml]
    responses:
      200:
        description: Response for successful request
        body:
          application/json:
            schema: restaurant-response
      400:
        description: Response for bad request
        body:
          application/json:
            schema: restaurant-response
      401:
        description: Response for unauthorized request
        body:
          application/json:
            schema: restaurant-response
      404:
        description: Response for resource not found
        body:
          application/json:
            schema: restaurant-response
      500:
        description: Response for internal error
        body:
          application/json:
            schema: restaurant-response
